services:
  web:
    build:
      context: .
    container_name: my_app_container
    restart: always
    ports:
      - "8000:8000"  # Проксируем порт 8000 с хоста на порт 8000 контейнера
    networks:
      - my_network
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: weather
    ports:
      - "5432:5432"  # Проксируем порт 5432 с хоста на порт 5432 контейнера
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  pgdata:
